baseURL = "https://bitcoin-dev.github.io/blog"
languageCode = "en-us"
title = "bitcoin-dev blog"

# Allows offline building.
ignoreErrors = ["error-remote-getjson"]

[params]
  images = [ "/img/og-image.png" ]
  description = "Bitcoin developers blogging about their open-source projects. A technical open-content blog."

[taxonomies]
  tag = 'tags'

[Social]
  twitter = "bitcoindevblog"

[outputFormats]
[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "feed"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true

  [privacy.twitter]
    # Do-Not-Track
    enableDNT = true

  [privacy.vimeo]
    # Do-Not-Track
    enableDNT = true

  [privacy.youtube]
    # YouTube won’t store information about visitors on your website unless the user plays the embedded video.
    privacyEnhanced = true


